// This is a simplified mock QR code for demonstration purposes
// In a real application, you would generate this dynamically and likely use a proper QR library
export const qrCodeMockData = `
PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIiB2aWV3Qm94PSIwIDAgMjEgMjEiPg0KICAgIDxyZWN0IHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSIgZmlsbD0iI2ZmZmZmZiIgLz4NCiAgICA8cGF0aCBkPSJNMSAxaDF2MWgxVjFoMXYxaC0xdjFoMXYxaC0xdi0xaC0xdjFoLTFWNGgxVjNoLTF6TTQgMWgxdjJoLTF6TTYgMWgxdjJoLTF6TTggMWgxdjFoMXYxaC0xdjFoLTF6TTEwIDFoMXYxaC0xek0xMiAxaDF2MWgtMXpNMTQgMWgxdjJoLTF6TTE2IDFoMXYxaDF2MWgtMXYxaC0xVjNoMXYtMWgtMXpNMTkgMWgxdjJoLTF6TTEgNGgxdjFoLTF6TTMgNGgydjFoLTJ6TTYgNGgydjFoLTJ6TTkgNGgxdjFoLTF6TTExIDRoMXYxaC0xek0xMyA0aDJ2MWgtMnpNMTkgNGgxdjFoLTF6TTEgNmgxdjJoLTF6TTMgNmgxdjFoMXYxaC0yeiIgZmlsbD0iIzAwMDAwMCIvPg0KICAgIDxwYXRoIGQ9Ik01IDZoMXYzaC0xek03IDZoMXYyaC0xek05IDZoMXYxaDF2MWgtMXYxaC0xeiIgZmlsbD0iIzAwMDAwMCIvPg0KICAgIDxwYXRoIGQ9Ik0xMiA2aDF2MWgtMXpNMTQgNmgxdjJoLTF6TTE2IDZoMXYzaC0xek0xOSA2aDF2MmgtMXpNNSAxMGgxdjJoLTF6TTggMTBoMnYxaC0yek0xMSAxMGgxdjFoLTF6TTE0IDEwaDF2MWgtMXpNMTkgMTBoMXYxaC0xek0xIDEyaDF2MWgxdjFoLTF2MWgtMXpNNCAxMmgxdjFoLTF6TTcgMTJoMXYxaC0xek05IDEyaDF2MWgtMXpNMTEgMTJoMXYxaC0xek0xMyAxMmgxdjFoLTF6TTE1IDEyaDF2MWgtMXpNMTcgMTJoMXYxaDF2MWgtMXYxaC0xek0xOSAxMmgxdjFoLTF6TTIgMTRoMnYxaC0yek01IDE0aDF2MWgtMXpNOCAxNGgxdjFoLTF6TTExIDE0aDF2MWgtMXpNMTQgMTRoMXYxaC0xek0yIDE2aDF2MWgxdjFoMXYxaC0xdi0xaC0xdi0xaC0xek00IDE2aDF2MWgtMXpNNiAxNmgxdjFoLTF6TTggMTZoMXYxaDF2MWgtMXYxaC0xeiIgZmlsbD0iIzAwMDAwMCIvPg0KICAgIDxwYXRoIGQ9Ik0xMCAxNmgxdjFoLTF6TTE0IDE2aDF2MWgxdjFoLTF2MWgtMXoiIGZpbGw9IiMwMDAwMDAiLz4NCiAgICA8cGF0aCBkPSJNMTYgMTZoMXYzaC0xek0xOSAxNmgxdjFoLTF6TTEgMThoMXYyaC0xek0xMSAxOGgxdjFoLTF6TTE5IDE4aDF2MmgtMXpNNCAxOWgxdjFoLTF6TTYgMTloMXYxaC0xek04IDE5aDF2MWgtMXpNMTIgMTloMXYxaC0xek0xNCAxOWgxdjFoLTF6IiBmaWxsPSIjMDAwMDAwIi8+DQo8L3N2Zz4=
`;

// Mock QR data for the code (this would be the actual data encoded in the QR)
export const mockSuperAdminQRData = {
  auth_type: "super_admin",
  timestamp: new Date().toISOString(),
  expiry: "600", // 10 minutes in seconds
  challenge: "a1b2c3d4e5f6g7h8i9j0"
};