import {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUp,
  BarChart,
  Box,
  Brain,
  Camera,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Code,
  Copy,
  Cpu,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Maximize,
  Minimize,
  Mic,
  Moon,
  MoreVertical,
  Play,
  Plus,
  QrCode,
  RefreshCw,
  Send,
  Settings,
  Share,
  SunMedium,
  Trash,
  Trophy,
  Twitter,
  Upload,
  User,
  VolumeX,
  Volume2,
  Wallet,
  X,
  type Icon as LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Cpu,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  twitter: Twitter,
  check: Check,
  warning: AlertTriangle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  billing: CreditCard,
  copy: Copy,
  file: File,
  plus: Plus,
  arrowUp: ArrowUp,
  barChart: BarChart,
  wallet: Wallet,
  brain: Brain,
  trophy: Trophy,
  play: Play,
  activity: Activity,
  moreVertical: MoreVertical,
  clock: Clock,
  calendar: Calendar,
  fileText: FileText,
  image: Image,
  
  // New icons for universal chatbot
  camera: Camera,
  mic: Mic,
  qrCode: QrCode,
  send: Send,
  refresh: RefreshCw,
  maximize: Maximize,
  minimize: Minimize,
  share: Share,
  upload: Upload,
  code: Code,
  volumeOn: Volume2,
  volumeOff: VolumeX,
  cube: Box, // For VR/AR
}