import {
  Bot,
  Camera,
  ChevronDown,
  ChevronUp,
  Copy,
  CreditCard,
  File,
  FileText,
  Github,
  Home,
  Landmark,
  LifeBuoy,
  LineChart,
  Loader2,
  LogOut,
  LucideProps,
  Mail,
  MessageSquare,
  Mic,
  Moon,
  MoreVertical,
  Package,
  Plus,
  QrCode,
  RefreshCw,
  Send,
  Settings,
  Star,
  Sun,
  Trash,
  Twitter,
  User,
  UserPlus,
  Users,
  X,
  Volume2,
  Maximize,
  Minimize,
  Image,
  Globe,
} from "lucide-react";

export type Icon = React.ReactElement<LucideProps>;

export const Icons = {
  logo: Bot,
  close: X,
  spinner: Loader2,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: LifeBuoy,
  user: User,
  arrowDown: ChevronDown,
  help: LifeBuoy,
  twitter: Twitter,
  check: RefreshCw,
  copy: Copy,
  gitHub: Github,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  laptop: Bot,
  users: Users,
  userPlus: UserPlus,
  mail: Mail,
  messageSquare: MessageSquare,
  home: Home,
  bank: Landmark,
  star: Star,
  mic: Mic,
  send: Send,
  camera: Camera,
  qrCode: QrCode,
  chart: LineChart,
  maximize: Maximize,
  minimize: Minimize,
  image: Image,
  globe: Globe,
  volume: Volume2,
  bot: Bot,
  package: Package,
};